config/routes.rb
Rails.application.routes.draw do
  root 'departments#index'
  resources :departments
  resources :expenses
  resources :members
  resources :tax_records
  resources :locations

end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :expenses
  has_many :members
  has_many :tax_records
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :department
  belongs_to :location

  def self.collection_cache_key
    latest         = order('updated_at DESC').take
    max_updated_at = [latest.updated_at, latest.location.updated_at].max
                     .try(:utc).try(:to_s, :number)
    [count,max_updated_at].join('-')
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :expenses
end

app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :department
end

app/models/tax_record.rb
class TaxRecord < ActiveRecord::Base
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

  def index
    @departments = Department.all
  end

  def show
    @department = Department.find(params[:id])
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def update
    l = Location.find(params[:id])
    l.update_attributes(location_params)
    redirect_to :back
  end

  def location_params
    params.require(:location).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
  def bia_cache_key_for(relationship)
    collection_cache_key = @department.send(relationship).collection_cache_key
    "dept/#{@department.id}/#{relationship}/all-#{collection_cache_key}"
  end
end

app/views/departments/index.html.erb
<h1>All departments</h1>
<hr />

<ul>
  <% @departments.each do |d| %>
    <li><%= link_to d.name, department_path(d) %></li>
  <% end %>
</ul>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>
<hr />

<div class='row'>
  <div class='large-4 columns'>
    <%= render 'expenses/index', expenses: @department.expenses.includes(:location) %>
  </div>

  <div class='large-4 columns'>
    <%= render 'members/index', members: @department.members %>
  </div>

  <div class='large-4 columns'>
    <%= render 'tax_records/index', tax_records: @department.tax_records %>
  </div>
</div>

<hr />
<p class='text-center'><%= Time.now %></p>

<div class='large-4 columns'>
  <%= form_for(Location.first) do |f| %>
  <div class='row'>
    <div class='large-8 columns'>
      <%= f.label :name, "Test the location change" %>
      <%= f.text_field :name %>
    </div>
    <div class='large-4 columns'>
      <br />
      <%= f.submit 'Update', class: 'tiny button radius' %>
    </div>
  </div>
  <% end %>
</div>

app/views/expenses/_expense.html.erb
<% cache([expense,expense.location]) do %>
<li class="bullet-item">
  <%= expense.name %><br />
  <%= expense.location.name %>
</li>
<% end %>

app/views/expenses/_index.html.erb
<% cache(bia_cache_key_for(:expenses)) do %>
<p class='text-center'><%= Time.now %></p>
<ul class="pricing-table">
  <li class="title">Expenses</li>
  <%= render expenses %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Cache Invalidation" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class='row'>
      <div class='large-12 columns'>
        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/members/_index.html.erb
<% cache(bia_cache_key_for(:members)) do %>
<p class='text-center'><%= Time.now %></p>
<ul class="pricing-table">
  <li class="title">Members</li>
  <%= render members %>
</ul>
<% end %>

app/views/members/_member.html.erb
<% cache(member) do %>
<li class="bullet-item"><%= member.name %></li>
<% end %>

app/views/tax_records/_index.html.erb
<% cache(bia_cache_key_for(:tax_records)) do %>
<p class='text-center'><%= Time.now %></p>
<ul class="pricing-table">
  <li class="title">Tax Records</li>
  <%= render tax_records %>
</ul>
<% end %>

app/views/tax_records/_tax_record.html.erb
<% cache(tax_record) do %>
<li class="bullet-item"><%= tax_record.name %></li>
<% end %>